### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by gamma** [splitbrain/dokuwiki-versionfix#4]
I tried to update a plugin version, but the dokuwiki.org site keeps nagging me.

First it threw a 403 at me; trying to log in using the Safari with correct credentials drops the server connection. Logging into the forum works OK. Using Chrome it does let me in.

Now the script sends a `Seems like something went wrong on editing the page plugin:imagemapping. Error was: Sorry, but the CAPTCHA wasn't answered correctly. Maybe you're not human at all?`

**Comment by splitbrain** [comment]
should work again
